server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://cn.dreamccc.cn:3306/pats?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: dzc9669
    hikari:
      keepalive-time: 10
      idle-timeout: 10
      max-lifetime: 10
      connection-timeout: 1000
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
  data:
    rest:
      base-path: /rest
      default-media-type: application/json
      return-body-on-create: true
      return-body-on-update: true
debug: true
logging:
  level:
    "root": INFO
    "run.bequick.dreamccc.pats": DEBUG
    "org.springframework.security": DEBUG
springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: spring-rest
      pathsToMatch: ["/rest/**"]
    - group: pats-server
      pathsToMatch: ["/**"]
      pathsToExclude: ["/rest/**"]
  show-login-endpoint: true
  cache:
    disabled: true