server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pats?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: dzc9669
    hikari:
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 20000
      #      keepalive-time: 6000
      #      leak-detection-threshold: 3000
      validation-timeout: 3000
      connection-timeout: 3000
      login-timeout: 3000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
  data:
    rest:
      base-path: /rest
      default-media-type: application/json
      return-body-on-create: true
      return-body-on-update: true
  redis:
    host: localhost
    port: 6379
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
  hateoas:
    use-hal-as-default-json-media-type: false
debug: true
logging:
  level:
    "root": INFO
    "run.bequick.dreamccc.pats": DEBUG
    "org.springframework.security": DEBUG
    "org.springframework.web.servlet.mvc.method.annotation": DEBUG
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} [%L] %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
springdoc:
  api-docs:
    groups:
      enabled: true
  group-configs:
    - group: spring-rest
      pathsToMatch: ["/rest/**"]
    - group: pats-server
      pathsToMatch: ["/**"]
      pathsToExclude: ["/rest/**"]
  show-login-endpoint: true
  cache:
    disabled: true